on:
  push:
    branches:
    - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies and run tests
        run: yarn install --frozen-lockfile

      - name: Build & Clean
        run: npx gatsby build && rm -rf .cache/

      - name: Prepare Screenshots Folder
        run: mkdir -p ./screenshots

      - name: Start Test Webserver in Background
        run: npx serve -s public -p 8000 &

      - name: Test
        run: yarn test

      - uses: actions/upload-artifact@v2
        with:
          name: test-screenshots
          path: ./screenshots
